name: GitHub Readme Guestbook

on:
  issues:
    types: [opened, deleted, edited]

jobs:
  update_guestbook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
      - run: npm install
      - name: Update guestbook
        uses: nfhipona/readme-guestbook@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_entries: 5
